### ISSUE TITLE
Can not install Tag plugin under Geeklog 2.1.2 Beta 2

### ISSUE THREAD

**Issue by ghost** [Geeklog-Plugins/tag#1]
Hello Developers,

Unfortunately the installation of the tag plugin does not work with Geeklog 2.1.2 Beta 2. If I upload the plugin normally normal in the plugin manager in the Geeklog back end, everything works out. But then the plugin can not be installed afterwards.

It is there, it came to the error and I have to look at the Error.log.

Can you please test this plugin with Geeklog 2.1.2 Beta 2 again. Maybe it is because of my server configuration or the Geeklog 2.1.2 installation.

Then I wait for your feedback.

Thanks in advance.

**Comment by mystralkk** [comment]
Thanks for reporting the error.  I confirmed the error you encountered and fixed it with change set 91ed41e.  Please use v0.6.2 on the GitHub.
